# Generated by Django 5.2.1 on 2025-05-25 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_rm', models.CharField(max_length=20, unique=True)),
                ('nik', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=10)),
                ('tempat_lahir', models.CharField(max_length=50)),
                ('tanggal_lahir', models.DateField()),
                ('agama', models.CharField(blank=True, max_length=20)),
                ('pekerjaan', models.CharField(blank=True, max_length=100)),
                ('nomor_hp', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenagaKesehatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('profesi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kunjungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_kunjungan', models.DateTimeField(auto_now_add=True)),
                ('jenis_pelayanan', models.CharField(choices=[('rawat_jalan', 'Rawat Jalan'), ('rawat_inap', 'Rawat Inap (Rujukan)'), ('gawat_darurat', 'Gawat Darurat (Rujukan)')], max_length=20)),
                ('keluhan_utama', models.TextField()),
                ('status', models.CharField(choices=[('diperiksa', 'Diperiksa'), ('dirujuk', 'Dirujuk'), ('selesai', 'Selesai')], default='diperiksa', max_length=50)),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kunjungan', to='core.pasien')),
            ],
        ),
        migrations.CreateModel(
            name='KontakDarurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('hubungan', models.CharField(max_length=50)),
                ('nomor_hp', models.CharField(max_length=20)),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontak_darurat', to='core.pasien')),
            ],
        ),
        migrations.CreateModel(
            name='Alamat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_alamat', models.CharField(choices=[('ktp', 'Alamat KTP'), ('domisili', 'Alamat Domisili')], max_length=50)),
                ('jalan', models.TextField()),
                ('rt_rw', models.CharField(blank=True, max_length=20)),
                ('kelurahan', models.CharField(max_length=100)),
                ('kecamatan', models.CharField(max_length=100)),
                ('kota', models.CharField(max_length=100)),
                ('provinsi', models.CharField(max_length=100)),
                ('kode_pos', models.CharField(max_length=10)),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alamat', to='core.pasien')),
            ],
        ),
        migrations.CreateModel(
            name='Penjamin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_penjamin', models.CharField(choices=[('bpjs', 'BPJS'), ('asuransi', 'Asuransi Lain')], max_length=50)),
                ('nama_penjamin', models.CharField(max_length=100)),
                ('nomor_kartu', models.CharField(max_length=50)),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penjamin', to='core.pasien')),
            ],
        ),
        migrations.CreateModel(
            name='RekamMedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anamnesis', models.TextField()),
                ('pemeriksaan_fisik', models.TextField()),
                ('terapi', models.TextField()),
                ('rencana_tindak_lanjut', models.TextField(blank=True, null=True)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('kunjungan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rekam_medis', to='core.kunjungan')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_icd10', models.CharField(max_length=10)),
                ('deskripsi', models.TextField()),
                ('rekam_medis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosa', to='core.rekammedis')),
            ],
        ),
        migrations.CreateModel(
            name='Rujukan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_rujukan', models.CharField(choices=[('rawat_inap', 'Rawat Inap'), ('gawat_darurat', 'Gawat Darurat')], max_length=50)),
                ('faskes_tujuan', models.CharField(max_length=200)),
                ('alasan', models.TextField()),
                ('kunjungan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rujukan', to='core.kunjungan')),
            ],
        ),
        migrations.CreateModel(
            name='LogAksesRekamMedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_akses', models.DateTimeField(auto_now_add=True)),
                ('catatan', models.TextField(blank=True)),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pasien')),
                ('tenaga_kesehatan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tenagakesehatan')),
            ],
        ),
        migrations.CreateModel(
            name='Tindakan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_icd9', models.CharField(blank=True, max_length=10)),
                ('nama_tindakan', models.TextField()),
                ('rekam_medis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tindakan', to='core.rekammedis')),
            ],
        ),
    ]
