# Generated by Django 5.2.1 on 2025-05-25 06:50

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Akses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_akses', models.CharField(max_length=100)),
                ('fitur', models.JSONField(default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name='diagnosa',
            name='rekam_medis',
        ),
        migrations.RemoveField(
            model_name='kontakdarurat',
            name='pasien',
        ),
        migrations.RemoveField(
            model_name='kunjungan',
            name='pasien',
        ),
        migrations.RemoveField(
            model_name='rujukan',
            name='kunjungan',
        ),
        migrations.RemoveField(
            model_name='rekammedis',
            name='kunjungan',
        ),
        migrations.RemoveField(
            model_name='logaksesrekammedis',
            name='pasien',
        ),
        migrations.RemoveField(
            model_name='logaksesrekammedis',
            name='tenaga_kesehatan',
        ),
        migrations.RemoveField(
            model_name='penjamin',
            name='pasien',
        ),
        migrations.RemoveField(
            model_name='tindakan',
            name='rekam_medis',
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('no_telp', models.CharField(blank=True, max_length=20)),
                ('peran', models.CharField(choices=[('admin_klinik', 'Admin Klinik'), ('owner', 'Owner'), ('user', 'User')], default='user', max_length=50)),
                ('akses_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.akses')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='pengguna_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='pengguna_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='Alamat',
        ),
        migrations.DeleteModel(
            name='Diagnosa',
        ),
        migrations.DeleteModel(
            name='KontakDarurat',
        ),
        migrations.DeleteModel(
            name='Rujukan',
        ),
        migrations.DeleteModel(
            name='Kunjungan',
        ),
        migrations.DeleteModel(
            name='LogAksesRekamMedis',
        ),
        migrations.DeleteModel(
            name='TenagaKesehatan',
        ),
        migrations.DeleteModel(
            name='Pasien',
        ),
        migrations.DeleteModel(
            name='Penjamin',
        ),
        migrations.DeleteModel(
            name='RekamMedis',
        ),
        migrations.DeleteModel(
            name='Tindakan',
        ),
    ]
