# Generated by Django 5.2.1 on 2025-05-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_akses_remove_diagnosa_rekam_medis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='akses',
            old_name='nama_akses',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='pengguna',
            old_name='no_telp',
            new_name='no_telepon',
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='peran',
            field=models.CharField(choices=[('admin_klinik', 'Admin Klinik'), ('owner', 'Owner'), ('user', 'User')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
