# Generated by Django 5.2.1 on 2025-05-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_nama_akses_akses_nama_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengguna',
            name='akses_admin',
        ),
        migrations.RemoveField(
            model_name='pengguna',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='pengguna',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Akses',
        ),
        migrations.DeleteModel(
            name='Pengguna',
        ),
    ]
