# Generated by Django 5.2.1 on 2025-05-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logaksesrekammedis',
            name='pasien',
        ),
        migrations.RemoveField(
            model_name='logaksesrekammedis',
            name='tenaga_kesehatan',
        ),
        migrations.RemoveField(
            model_name='rujukan',
            name='kunjungan',
        ),
        migrations.RemoveField(
            model_name='tindakan',
            name='rekam_medis',
        ),
        migrations.AlterModelOptions(
            name='icd10',
            options={'verbose_name_plural': 'Master Data ICD-10'},
        ),
        migrations.RenameField(
            model_name='kunjungan',
            old_name='diagnosis',
            new_name='diagnosisbycode',
        ),
        migrations.RemoveField(
            model_name='kunjungan',
            name='jenis_pelayanan',
        ),
        migrations.AlterField(
            model_name='pasien',
            name='agama',
            field=models.CharField(choices=[('islam', 'Islam'), ('kristen', 'Kristen'), ('hindu', 'Hindu'), ('buddha', 'Buddha'), ('konghucu', 'Konghucu')]),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='pekerjaan',
            field=models.CharField(choices=[('belum kerja', 'Belum Kerja'), ('pelajar', 'Pelajar'), ('mahasiswa', 'Mahasiswa'), ('mengurus rumah tangga', 'Mengurus Rumah Tangga'), ('pensiunan', 'Pensiunan'), ('pns', 'PNS'), ('tni/polri', 'TNI/Polri'), ('karyawan swasta', 'Karyawan Swasta'), ('karyawan bu', 'Karyawan BUMN/BUMD'), ('pengusaha', 'Pengusaha'), ('lainnya', 'Lainnya')]),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='pendidikan',
            field=models.CharField(choices=[('belum-sekolah', 'Belum Sekolah'), ('sd-sederajat', 'SD/Sederajat'), ('smp-sederajat', 'SMP/Sederajat'), ('sma-sederajat', 'SMA/Sederajat'), ('d3', 'D3'), ('s1', 'S1'), ('s2', 'S2'), ('s3', 'S3')]),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='status_pernikahan',
            field=models.CharField(choices=[('belum nikah', 'Belum Nikah'), ('nikah', 'Nikah'), ('cerai hidup', 'Cerai Hidup'), ('cerai mati', 'Cerai Mati')]),
        ),
        migrations.DeleteModel(
            name='Diagnosa',
        ),
        migrations.DeleteModel(
            name='LogAksesRekamMedis',
        ),
        migrations.DeleteModel(
            name='TenagaKesehatan',
        ),
        migrations.DeleteModel(
            name='Rujukan',
        ),
        migrations.DeleteModel(
            name='Tindakan',
        ),
    ]
