# Generated by Django 5.2.1 on 2025-05-29 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_logaksesrekammedis_pasien_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField()),
                ('deskripsi', models.CharField()),
            ],
            options={
                'verbose_name_plural': 'Master Data Jenis Alergi',
            },
        ),
        migrations.CreateModel(
            name='Layanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('bentuk', models.CharField(choices=[('tablet', 'Tablet'), ('kapsul', 'Kapsul'), ('sirup', 'Sirup'), ('salep', 'Salep'), ('injeksi', 'Injeksi'), ('tetes', 'Tetes'), ('suppositoria', 'Suppositoria'), ('lainnya', 'Lainnya')], default='tablet', max_length=50)),
                ('dosis', models.CharField(max_length=100)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Penyakit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField()),
                ('deskripsi', models.CharField()),
            ],
            options={
                'verbose_name_plural': 'Master Data Jenis Penyakit',
            },
        ),
        migrations.CreateModel(
            name='Tindakan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vaksin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='rekammedis',
            name='kunjungan',
        ),
        migrations.AlterModelOptions(
            name='rekammedis',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Rekam Medis'},
        ),
        migrations.RenameField(
            model_name='rekammedis',
            old_name='tanggal_dibuat',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='pasien',
            name='golongan_darah',
            field=models.CharField(blank=True, choices=[('o', 'O'), ('a', 'A'), ('b', 'B'), ('ab', 'AB'), ('', '-')], null=True),
        ),
        migrations.AddField(
            model_name='pasien',
            name='status',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Tidak Aktif')], default='aktif', max_length=10),
        ),
        migrations.AddField(
            model_name='pasien',
            name='status_merokok',
            field=models.CharField(blank=True, choices=[('merokok', 'Merokok'), ('tidak_merokok', 'Tidak Merokok'), ('', '-')], null=True),
        ),
        migrations.AddField(
            model_name='rekammedis',
            name='berat_badan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rekammedis',
            name='catatan_diagnosis',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rekammedis',
            name='catatan_riwayat_alergi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rekammedis',
            name='catatan_riwayat_penyakit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rekammedis',
            name='diastole',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rekammedis',
            name='frekuensi_pernafasan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rekammedis',
            name='keluhan_utama',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rekammedis',
            name='kode_diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.icd10'),
        ),
        migrations.AddField(
            model_name='rekammedis',
            name='nadi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rekammedis',
            name='pasien',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='kunjungan', to='core.pasien'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rekammedis',
            name='sistole',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rekammedis',
            name='status_kesadaran',
            field=models.CharField(choices=[('CM', 'Compos Mentis'), ('AP', 'Apatis'), ('SL', 'Somnolen'), ('SP', 'Sopor'), ('C', 'Coma')], default='CM', max_length=20),
        ),
        migrations.AddField(
            model_name='rekammedis',
            name='suhu_tubuh',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rekammedis',
            name='tinggi_badan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rekammedis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='icd10',
            name='deskripsi',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='agama',
            field=models.CharField(blank=True, choices=[('islam', 'Islam'), ('kristen_protestan', 'Kristen Protestan'), ('katolik', 'Katolik'), ('hindu', 'Hindu'), ('buddha', 'Buddha'), ('konghucu', 'Konghucu'), ('kepercayaan_lain', 'Kepercayaan Lain')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='alamat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='jenis_kelamin',
            field=models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='nik',
            field=models.CharField(default=0, max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pasien',
            name='nomor_hp',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='pekerjaan',
            field=models.CharField(blank=True, choices=[('belum_kerja', 'Belum Bekerja'), ('pelajar_mahasiswa', 'Pelajar/Mahasiswa'), ('ibu_rumah_tangga', 'Mengurus Rumah Tangga'), ('pensiunan', 'Pensiunan'), ('pns', 'PNS'), ('tni_polri', 'TNI/Polri'), ('karyawan_swasta', 'Karyawan Swasta'), ('karyawan_bumn', 'Karyawan BUMN/BUMD'), ('pengusaha', 'Pengusaha'), ('lainnya', 'Lainnya')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='pendidikan',
            field=models.CharField(blank=True, choices=[('belum_sekolah', 'Belum Sekolah'), ('sd', 'SD/Sederajat'), ('smp', 'SMP/Sederajat'), ('sma', 'SMA/Sederajat'), ('d3', 'Diploma 3 (D3)'), ('s1', 'Sarjana (S1)'), ('s2', 'Magister (S2)'), ('s3', 'Doktor (S3)'), ('lainnya', 'Lainnya')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='status_pernikahan',
            field=models.CharField(blank=True, choices=[('belum_nikah', 'Belum Nikah'), ('nikah', 'Nikah'), ('cerai_hidup', 'Cerai Hidup'), ('cerai_mati', 'Cerai Mati'), ('lainnya', 'Lainnya')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rekammedis',
            name='riwayat_alergi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.alergi'),
        ),
        migrations.AddField(
            model_name='rekammedis',
            name='layanan_atau_tindakan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.layanan'),
        ),
        migrations.AddField(
            model_name='rekammedis',
            name='riwayat_penyakit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.penyakit'),
        ),
        migrations.CreateModel(
            name='Registrasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('waktu', models.TimeField(auto_now_add=True)),
                ('no_antrian', models.PositiveIntegerField(blank=True)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu Konsultasi'), ('selesai', 'Selesai Konsultasi'), ('batal', 'Dibatalkan')], default='menunggu', max_length=20)),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrasi', to='core.pasien')),
            ],
            options={
                'verbose_name_plural': 'Registrasi',
                'ordering': ['-tanggal', 'no_antrian'],
            },
        ),
        migrations.AddField(
            model_name='rekammedis',
            name='registrasi',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rekam_medis', to='core.registrasi'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RekamMedisObat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('catatan', models.TextField(blank=True, null=True)),
                ('obat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.obat')),
                ('rekam_medis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obat_diberikan', to='core.rekammedis')),
            ],
        ),
        migrations.AddField(
            model_name='rekammedis',
            name='vaksin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vaksin'),
        ),
        migrations.DeleteModel(
            name='Kunjungan',
        ),
    ]
