# Generated by Django 5.2.1 on 2025-05-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alergi_layanan_obat_penyakit_tindakan_vaksin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layanan',
            options={'verbose_name_plural': 'Master Data Layanan'},
        ),
        migrations.AlterModelOptions(
            name='obat',
            options={'verbose_name_plural': 'Master Data Obat'},
        ),
        migrations.AlterModelOptions(
            name='tindakan',
            options={'verbose_name_plural': 'Master Data Tindakan'},
        ),
        migrations.AlterModelOptions(
            name='vaksin',
            options={'verbose_name_plural': 'Master Data Vaksin'},
        ),
        migrations.RemoveField(
            model_name='obat',
            name='dosis',
        ),
        migrations.AddField(
            model_name='obat',
            name='dosis_nilai',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obat',
            name='dosis_satuan',
            field=models.CharField(choices=[('mg', 'mg'), ('mL', 'mL'), ('IU', 'IU'), ('tablet', 'Tablet'), ('kapsul', 'Kapsul'), ('unit', 'Unit'), ('cc', 'cc')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pasien',
            name='golongan_darah',
            field=models.CharField(blank=True, choices=[('o', 'O'), ('a', 'A'), ('b', 'B'), ('ab', 'AB'), ('', '-')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='status_merokok',
            field=models.CharField(blank=True, choices=[('merokok', 'Merokok'), ('tidak_merokok', 'Tidak Merokok'), ('', '-')], max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='icd10',
            unique_together={('kode', 'deskripsi')},
        ),
    ]
