# Generated by Django 5.2.1 on 2025-05-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_layanan_options_alter_obat_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obat',
            name='dosis_nilai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
