# Generated by Django 5.2.1 on 2025-05-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_obat_dosis_nilai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obat',
            name='dosis_nilai',
            field=models.IntegerField(default=1),
        ),
    ]
