# Generated by Django 5.2.1 on 2025-05-30 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_obat_dosis_nilai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rekammedis',
            name='pasien',
        ),
        migrations.AlterField(
            model_name='obat',
            name='dosis_satuan',
            field=models.CharField(choices=[('g', 'gram'), ('mg', 'mg'), ('ml', 'ml'), ('IU', 'IU'), ('tablet', 'Tablet'), ('kapsul', 'Kapsul'), ('unit', 'Unit'), ('cc', 'cc'), ('ampul', 'Ampul'), ('tetes', 'Tetes')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='agama',
            field=models.CharField(blank=True, choices=[('islam', 'Islam'), ('kristen_protestan', 'Kristen Protestan'), ('katolik', 'Katolik'), ('hindu', 'Hindu'), ('buddha', 'Buddha'), ('konghucu', 'Konghucu'), ('kepercayaan_lain', 'Kepercayaan Lain'), ('', '-')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='jenis_kelamin',
            field=models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan'), ('', '-')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='pekerjaan',
            field=models.CharField(blank=True, choices=[('belum_kerja', 'Belum Bekerja'), ('pelajar_mahasiswa', 'Pelajar/Mahasiswa'), ('ibu_rumah_tangga', 'Mengurus Rumah Tangga'), ('pensiunan', 'Pensiunan'), ('pns', 'PNS'), ('tni_polri', 'TNI/Polri'), ('karyawan_swasta', 'Karyawan Swasta'), ('karyawan_bumn', 'Karyawan BUMN/BUMD'), ('pengusaha', 'Pengusaha'), ('lainnya', 'Lainnya'), ('', '-')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='pendidikan',
            field=models.CharField(blank=True, choices=[('belum_sekolah', 'Belum Sekolah'), ('sd', 'SD/Sederajat'), ('smp', 'SMP/Sederajat'), ('sma', 'SMA/Sederajat'), ('d3', 'Diploma 3 (D3)'), ('s1', 'Sarjana (S1)'), ('s2', 'Magister (S2)'), ('s3', 'Doktor (S3)'), ('lainnya', 'Lainnya'), ('', '-')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='status_pernikahan',
            field=models.CharField(blank=True, choices=[('belum_nikah', 'Belum Nikah'), ('nikah', 'Nikah'), ('cerai_hidup', 'Cerai Hidup'), ('cerai_mati', 'Cerai Mati'), ('lainnya', 'Lainnya'), ('', '-')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rekammedis',
            name='catatan_diagnosis',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rekammedis',
            name='kode_diagnosis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.icd10'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rekammedisobat',
            name='catatan',
            field=models.CharField(blank=True, null=True),
        ),
    ]
