# Generated by Django 5.2.1 on 2025-05-30 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_rekammedis_pasien_alter_obat_dosis_satuan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rekammedis',
            name='layanan_atau_tindakan',
        ),
        migrations.RemoveField(
            model_name='rekammedis',
            name='vaksin',
        ),
        migrations.AlterField(
            model_name='rekammedis',
            name='berat_badan',
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rekammedis',
            name='diastole',
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rekammedis',
            name='frekuensi_pernafasan',
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rekammedis',
            name='nadi',
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rekammedis',
            name='sistole',
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rekammedis',
            name='suhu_tubuh',
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rekammedis',
            name='tinggi_badan',
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='RekamMedisLayanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catatan', models.CharField(blank=True, max_length=255, null=True)),
                ('layanan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.layanan')),
                ('rekam_medis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layanan_diberikan', to='core.rekammedis')),
            ],
        ),
        migrations.CreateModel(
            name='RekamMedisTindakan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catatan', models.CharField(blank=True, max_length=255, null=True)),
                ('rekam_medis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tindakan_diberikan', to='core.rekammedis')),
                ('tindakan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tindakan')),
            ],
        ),
        migrations.CreateModel(
            name='RekamMedisVaksin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catatan', models.CharField(blank=True, max_length=255, null=True)),
                ('rekam_medis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaksin_diberikan', to='core.rekammedis')),
                ('vaksin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vaksin')),
            ],
        ),
    ]
