# Generated by Django 5.2.1 on 2025-06-02 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_rekammedis_berat_badan_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='icd10',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='icd10',
            name='bab',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='layanan',
            name='kategori',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obat',
            name='harga',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tindakan',
            name='kategori',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tindakan',
            name='kode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vaksin',
            name='harga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alergi',
            name='deskripsi',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='icd10',
            name='deskripsi',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='penyakit',
            name='deskripsi',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='icd10',
            unique_together={('bab', 'kode', 'deskripsi')},
        ),
        migrations.CreateModel(
            name='Tagihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status_pembayaran', models.CharField(choices=[('belum_lunas', 'Belum Lunas'), ('lunas', 'Lunas')], default='belum_lunas', max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('registrasi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.registrasi')),
            ],
            options={
                'verbose_name_plural': 'Tagihan',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='ItemTagihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('layanan', 'Layanan'), ('tindakan', 'Tindakan'), ('obat', 'Obat'), ('vaksin', 'Vaksin'), ('lainnya', 'Lainnya')], max_length=20)),
                ('nama', models.CharField(max_length=255)),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('tagihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.tagihan')),
            ],
            options={
                'verbose_name_plural': 'Item Tagihan',
            },
        ),
    ]
