# Generated by Django 5.2.1 on 2025-06-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_icd10_unique_together_icd10_bab_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rekammedislayanan',
            name='layanan',
        ),
        migrations.RemoveField(
            model_name='rekammedislayanan',
            name='rekam_medis',
        ),
        migrations.RemoveField(
            model_name='tagihan',
            name='registrasi',
        ),
        migrations.RemoveField(
            model_name='obat',
            name='harga',
        ),
        migrations.RemoveField(
            model_name='tindakan',
            name='harga',
        ),
        migrations.DeleteModel(
            name='ItemTagihan',
        ),
        migrations.DeleteModel(
            name='Layanan',
        ),
        migrations.DeleteModel(
            name='RekamMedisLayanan',
        ),
        migrations.DeleteModel(
            name='Tagihan',
        ),
    ]
