# Generated by Django 5.2.1 on 2025-06-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_rekammedislayanan_layanan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rekammedis',
            name='riwayat_alergi',
            field=models.CharField(blank=True, default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rekammedis',
            name='riwayat_penyakit',
            field=models.CharField(blank=True, default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='rekammedisvaksin',
            name='rekam_medis',
        ),
        migrations.RemoveField(
            model_name='rekammedisvaksin',
            name='vaksin',
        ),
        migrations.RemoveField(
            model_name='rekammedis',
            name='catatan_riwayat_alergi',
        ),
        migrations.RemoveField(
            model_name='rekammedis',
            name='catatan_riwayat_penyakit',
        ),
        migrations.AddField(
            model_name='pasien',
            name='jenis_pasien',
            field=models.CharField(choices=[('umum', 'Umum'), ('bpjs', 'BPJS'), ('asuransi_lain', 'Asuransi Lain')], default='umum', max_length=30),
        ),
        migrations.AddField(
            model_name='pasien',
            name='no_asuransi',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rekammedis',
            name='prognosis',
            field=models.CharField(choices=[('sanam', 'Sanam'), ('bonam', 'Bonam'), ('malam', 'Malam'), ('dubia', 'Dubia')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pasien',
            name='jenis_kelamin',
            field=models.CharField(choices=[('l', 'Laki-laki'), ('p', 'Perempuan'), ('', '-')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='pekerjaan',
            field=models.CharField(blank=True, choices=[('belum_kerja', 'Belum Bekerja'), ('pelajar_mahasiswa', 'Pelajar/Mahasiswa'), ('ibu_rumah_tangga', 'Mengurus Rumah Tangga'), ('guru', 'Guru'), ('pensiunan', 'Pensiunan'), ('pns', 'PNS'), ('tni_polri', 'TNI/Polri'), ('karyawan_swasta', 'Karyawan Swasta'), ('karyawan_bumn', 'Karyawan BUMN/BUMD'), ('pengusaha', 'Pengusaha'), ('lainnya', 'Lainnya'), ('', '-')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='status_pernikahan',
            field=models.CharField(blank=True, choices=[('belum_nikah', 'Belum Nikah'), ('nikah', 'Nikah'), ('cerai_hidup', 'Cerai Hidup'), ('cerai_mati', 'Cerai Mati'), ('', '-')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rekammedis',
            name='status_kesadaran',
            field=models.CharField(choices=[('cm', 'Compos Mentis'), ('ap', 'Apatis'), ('sl', 'Somnolen'), ('sp', 'Sopor'), ('c', 'Coma')], default='cm', max_length=20),
        ),
        migrations.DeleteModel(
            name='Alergi',
        ),
        migrations.DeleteModel(
            name='Penyakit',
        ),
        migrations.DeleteModel(
            name='RekamMedisVaksin',
        ),
    ]
