# Generated by Django 5.2.1 on 2025-06-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_rekammedis_riwayat_alergi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasien',
            name='jenis_pasien',
            field=models.CharField(blank=True, choices=[('umum', 'Umum'), ('bpjs', 'BPJS'), ('asuransi_lain', 'Asuransi Lain')], default='umum', max_length=30, null=True),
        ),
    ]
