# Generated by Django 5.2.1 on 2025-06-08 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_catatan_diagnosis_rekammedis_diagnosis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResepObat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_obat', models.CharField(blank=True, max_length=255, null=True)),
                ('jumlah', models.CharField(blank=True, max_length=5, null=True)),
                ('bentuk', models.CharField(blank=True, choices=[('tablet', 'Tablet'), ('kapsul', 'Kapsul'), ('sirup', 'Sirup'), ('salep', 'Salep'), ('injeksi', 'Injeksi'), ('tetes', 'Tetes'), ('suppositoria', 'Suppositoria'), ('lainnya', 'Lainnya')], max_length=50, null=True)),
                ('bentuk_lainnya', models.CharField(blank=True, max_length=50, null=True)),
                ('dosis_nilai', models.PositiveIntegerField(blank=True, help_text='Contoh: 500, 5, dll', null=True)),
                ('frekuensi', models.CharField(blank=True, choices=[('1x1', '1x sehari'), ('2x1', '2x sehari'), ('3x1', '3x sehari'), ('4x1', '4x sehari'), ('prn', 'Sesuai kebutuhan (PRN)'), ('lainnya', 'Lainnya')], max_length=20, null=True)),
                ('frekuensi_lainnya', models.CharField(blank=True, max_length=255, null=True)),
                ('dosis_satuan', models.CharField(blank=True, choices=[('mg', 'Miligram (mg)'), ('g', 'Gram (g)'), ('ml', 'Mililiter (ml)'), ('cc', 'cc'), ('IU', 'International Unit (IU)'), ('tablet', 'Tablet'), ('kapsul', 'Kapsul'), ('ampul', 'Ampul'), ('tetes', 'Tetes'), ('sdm', 'Sendok Makan'), ('sdt', 'Sendok Teh'), ('lainnya', 'Lainnya')], max_length=20, null=True)),
                ('dosis_satuan_lainnya', models.CharField(blank=True, max_length=255, null=True)),
                ('aturan_pakai', models.CharField(blank=True, choices=[('sebelum_makan', 'Sebelum makan'), ('sesudah_makan', 'Sesudah makan'), ('sebelum_tidur', 'Sebelum tidur'), ('setelah_bangun', 'Setelah bangun tidur'), ('dengan_makanan', 'Bersama makanan'), ('lainnya', 'Lainnya')], max_length=50, null=True)),
                ('aturan_pakai_lainnya', models.CharField(blank=True, max_length=255, null=True)),
                ('rekam_medis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resep_obat', to='core.rekammedis')),
            ],
        ),
        migrations.RemoveField(
            model_name='rekammedisobat',
            name='obat',
        ),
        migrations.RemoveField(
            model_name='rekammedisobat',
            name='rekam_medis',
        ),
        migrations.RemoveField(
            model_name='rekammedistindakan',
            name='rekam_medis',
        ),
        migrations.RemoveField(
            model_name='rekammedistindakan',
            name='tindakan',
        ),
        migrations.DeleteModel(
            name='Vaksin',
        ),
        migrations.AlterUniqueTogether(
            name='icd10',
            unique_together={('kode', 'deskripsi')},
        ),
        migrations.DeleteModel(
            name='Obat',
        ),
        migrations.DeleteModel(
            name='RekamMedisObat',
        ),
        migrations.DeleteModel(
            name='RekamMedisTindakan',
        ),
        migrations.DeleteModel(
            name='Tindakan',
        ),
        migrations.RemoveField(
            model_name='icd10',
            name='bab',
        ),
    ]
