# Generated by Django 5.2.1 on 2025-06-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_resepobat_remove_rekammedisobat_obat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rekammedis',
            name='berat_badan',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rekammedis',
            name='suhu_tubuh',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
