# Generated by Django 5.2.1 on 2025-06-11 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_rekammedis_berat_badan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasien',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('l', 'Laki-laki'), ('p', 'Perempuan'), ('', '-')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='nama_lengkap',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='nik',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='no_rm',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='status',
            field=models.CharField(blank=True, choices=[('aktif', 'Aktif'), ('nonaktif', 'Tidak Aktif')], default='aktif', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rekammedis',
            name='berat_badan',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rekammedis',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rekammedis',
            name='keluhan_utama',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rekammedis',
            name='kode_diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.icd10'),
        ),
        migrations.AlterField(
            model_name='rekammedis',
            name='prognosis',
            field=models.CharField(blank=True, choices=[('sanam', 'Sanam'), ('bonam', 'Bonam'), ('malam', 'Malam'), ('dubia', 'Dubia')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rekammedis',
            name='riwayat_alergi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rekammedis',
            name='riwayat_penyakit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rekammedis',
            name='status_kesadaran',
            field=models.CharField(blank=True, choices=[('cm', 'Compos Mentis'), ('ap', 'Apatis'), ('sl', 'Somnolen'), ('sp', 'Sopor'), ('c', 'Coma')], default='cm', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='ResepObat',
        ),
    ]
