# Generated by Django 5.2.1 on 2025-06-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_pasien_jenis_kelamin_alter_pasien_nama_lengkap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rekammedis',
            name='suhu_tubuh',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
