# Generated by Django 5.2.1 on 2025-06-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_rekammedis_suhu_tubuh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasien',
            name='agama',
            field=models.CharField(blank=True, choices=[('islam', 'Islam'), ('kristen_protestan', 'Kristen Protestan'), ('katolik', 'Katolik'), ('hindu', 'Hindu'), ('buddha', 'Buddha'), ('konghucu', 'Konghucu'), ('kepercayaan_lain', 'Kepercayaan Lain')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='golongan_darah',
            field=models.CharField(blank=True, choices=[('o', 'O'), ('a', 'A'), ('b', 'B'), ('ab', 'AB')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('l', 'Laki-laki'), ('p', 'Perempuan')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='pekerjaan',
            field=models.CharField(blank=True, choices=[('belum_kerja', 'Belum Bekerja'), ('pelajar_mahasiswa', 'Pelajar/Mahasiswa'), ('ibu_rumah_tangga', 'Mengurus Rumah Tangga'), ('guru', 'Guru'), ('pensiunan', 'Pensiunan'), ('pns', 'PNS'), ('tni_polri', 'TNI/Polri'), ('karyawan_swasta', 'Karyawan Swasta'), ('karyawan_bumn', 'Karyawan BUMN/BUMD'), ('pengusaha', 'Pengusaha'), ('lainnya', 'Lainnya')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='pendidikan',
            field=models.CharField(blank=True, choices=[('belum_sekolah', 'Belum Sekolah'), ('sd', 'SD/Sederajat'), ('smp', 'SMP/Sederajat'), ('sma', 'SMA/Sederajat'), ('d3', 'Diploma 3 (D3)'), ('s1', 'Sarjana (S1)'), ('s2', 'Magister (S2)'), ('s3', 'Doktor (S3)'), ('lainnya', 'Lainnya')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='status_merokok',
            field=models.CharField(blank=True, choices=[('merokok', 'Merokok'), ('tidak_merokok', 'Tidak Merokok')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='status_pernikahan',
            field=models.CharField(blank=True, choices=[('belum_nikah', 'Belum Nikah'), ('nikah', 'Nikah'), ('cerai_hidup', 'Cerai Hidup'), ('cerai_mati', 'Cerai Mati')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rekammedis',
            name='medikamentosa',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rekammedis',
            name='non_medikamentosa',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
