# Generated by Django 5.2.1 on 2025-06-12 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rekammedis_created_by_rekammedis_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rekammedis',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rekammedis_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rekammedis',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rekammedis_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
