# Generated by Django 5.2.3 on 2025-06-26 02:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_rekammedis_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rekammedis',
            name='plan',
            field=ckeditor.fields.RichTextField(default=0),
            preserve_default=False,
        ),
    ]
