# Generated by Django 5.2.3 on 2025-06-26 02:56

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_rekammedis_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rekammedis',
            name='plan',
        ),
        migrations.AddField(
            model_name='rekammedis',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(default=0, verbose_name='Text'),
            preserve_default=False,
        ),
    ]
