# Generated by Django 5.2.3 on 2025-06-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_rekammedis_plan_rekammedis_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rekammedis',
            name='text',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
