# Generated by Django 5.2.3 on 2025-06-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_rekammedis_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rekammedis',
            old_name='diagnosis',
            new_name='diagnosis_deskripsi',
        ),
        migrations.AlterField(
            model_name='rekammedis',
            name='kode_diagnosis',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
