# Generated by Django 5.2.3 on 2025-06-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_rename_diagnosis_rekammedis_diagnosis_deskripsi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rekammedis',
            name='kode_diagnosis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
